### ISSUE TITLE
Kafka Usage

### ISSUE THREAD

**Issue by omarKabdou** [mserrate/twitter-streaming-app#1]
Hi @mserrate! I was wondering if there is a specific reason for using Kafka rather than consuming the stream by storm directly from the Twitter API?

**Comment by mserrate** [comment]
Hi @OmarKhaledAbdo, no specific reason just showing a technical end-to-end example. That being said, one advantage to have Kafka in this case would be the ability to reprocess the tweets from the beginning without relying to an external API.
